#!/usr/bin/env bash
# Install Nginx on Web-Sever-01

# Update Packages first before making Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configure Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx configs for Syntax errors
sudo nginx -t

# Restart Nginx
sudo service nginx start
