#!/usr/bin/env bash
# This script configures Nginx on a new Ubuntu machine to add a custom HTTP response header.

# Install Nginx (if not already installed)
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to include the custom header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test configurations for syntax errors
sudo nginx -t

# Reload Nginx to apply the changes
sudo service nginx restart
