#!/bin/bash

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
frontend web_frontend
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server web-01 100.25.119.84:80 check
    server web-02 54.197.113.176:80 check

EOL

# Restart HAProxy to apply changes
#sudo systemctl restart haproxy
sudo service haproxy restart


# Enable HAProxy to start on boot
#sudo systemctl enable haproxy
sudo service haproxy enable


