#!/bin/bash
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HAProxy
# Description:       HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/haproxy
NAME=haproxy
DESC=haproxy

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        $DAEMON -f /etc/haproxy/haproxy.cfg
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        killall -9 haproxy
        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        killall -9 haproxy
        sleep 1
        $DAEMON -f /etc/haproxy/haproxy.cfg
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

sudo service haproxy start

exit 0
