#!/usr/bin/env bash
# script that restores the default server port

# Backup the default Nginx configuration
mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
