#!/usr/bin/env bash
# script of task 0 but using less lines
mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak # Backup the default Nginx configuration
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
