#!/usr/bin/env bash
# Install Nginx


apt-get update
apt-get install -y nginx

# Create a custom 404 page with the required content
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/404.html

# Configure Nginx to use the custom 404 page
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    location = /50x.html {
        internal;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;
    }
}
EOL

# Test Nginx configuration
nginx -t

# Restart Nginx to apply changes
service nginx restart
