#!/usr/bin/env bash
# This script connects to the server using ssh with a private key

# Set the correct path to the private key
private_key_path="~/.ssh/school"

# Connect to the server using ssh with the specified private key
ssh -i "$private_key_path" ubuntu@100.25.119.84
